### ISSUE TITLE
send your discord

### ISSUE THREAD

**Issue by FightorDiee** [xortoproject/xortostealer#2]
in my webhock i received a invite but i can't join, send me another invite pls

**Comment by neilasa999** [comment]
did you get another link?

**Comment by fewerstealer2** [comment]
https://t.me/fewerstealerv2

**Comment by huedini1** [comment]
arustler.

**Comment by Azizishot** [comment]
[> in my webhock i received a invite but i can't join, send me another invite pls

[](https://discord.gg/q5uqjs4f4u)](https://discord.gg/q5uqjs4f4u)

**Comment by xortoproject** [comment]
https://t.me/xortoproject
