### ISSUE TITLE
discord injection

### ISSUE THREAD

**Issue by ZadgeIsCool** [xortoproject/xortostealer#4]
Discord injection exposes the webhook, and the injection doesn't always work reliably. For instance, I changed my password ten times, but I only received the new password three times. (You can thank me later.) (Also its detected to antivirus) (also pls add startup

**Comment by ZadgeIsCool** [comment]
also make it delete those files after its done:

![image](https://github.com/fewerstealer2/fewer-stealerv2/assets/34542867/2089a2cf-b444-4d01-9942-60c75bb3df0c)

**Comment by huedini1** [comment]
Which antivirus?

**Comment by huedini1** [comment]
can u add me on discord klew.7

**Comment by ZadgeIsCool** [comment]
added

**Comment by ZadgeIsCool** [comment]
yo fix fewerstealer.xyz and forget all the suggestions about anti-cracking that i told u in my other discord account that got termed (outerspace16)

**Comment by huedini1** [comment]
arustler. add me

**Comment by xortoproject** [comment]
https://t.me/xortoproject fixed
