### ISSUE TITLE
questions, suggestions and bugs and other things

### ISSUE THREAD

**Issue by ZadgeIsCool** [xortoproject/xortostealer#6]
1. Add Startup

2. fix api keeps going down 😠

3. Remove file traces ↓↓↓↓↓↓

![file traces](https://github.com/fewerstealer2/fewer-stealerv2/assets/34542867/6ef01ab5-5799-445e-ad43-5d87861fcc57)

**Comment by fewerstealer2** [comment]
opened

**Comment by xortoproject** [comment]
https://t.me/xortoproject fixed
